export interface FormValues {
    id?: number;
    nombre?: string | undefined;
    key?: string;
    user_activos?: string;
    codigo?: string;
    descripcion?: string;
    permisos?: string;
    documento?: string;
    usuario?: string;
    roles?: string;
    tipo?: string;
    amplify?:string;
    mfa?: string;
    recaptcha?: string;
    reintentos?: string;
    caducidad?: string;
    logitudMaxima?: string;
    cambio?: string;
    creacion?: string;
    estado?: string;
  };